package org.weathersensor.SpringRESTWeatherSensor.models;

public class Measurement {

//
//    id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//    sensor_id int REFERENCES sensor(id),
//    value   float4,
//    raining boolean NOT NULL,
//    time    timestamp

}
