openapi: 3.0.3
info:
  title: Operator
  version: "1.0.0"
servers:
  - url: http://localhost:6060
    description: Dev Server
tags:
  - name: operator
    description: managing operators

paths:
  /operators:
    get:
      summary: Get operators
      description: Returns all/filtered by name or number operators
      tags:
        - operator
      operationId: getOperators
      parameters:
        - $ref: '#/components/parameters/name'
        - $ref: '#/components/parameters/personalNumber'
      responses:
        '200':
          description: Returns an array of operators
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OperatorDTO'
        '204':
          description: No data
          content: {}
        '404':
          description: Not found
#          content:
#            application/json:
#              schema:
#                $ref: ''
        '500':
          description: Internal server error
  /operators/{operatorId}:
    get:
      description: Returns an operator
      tags:
        - operator
      parameters:
        - $ref: '#/components/parameters/operatorId'
      operationId: getOperator

      responses:
        '200':
          description: Returns an operator
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperatorDTO'
        '204':
          description: No data
          content: {}
        '404':
          description: Not found
        '500':
          description: Internal server error
components:

  parameters:
    name:
      name: name
      in: query
      description: Operator's name
      required: false
      schema:
        type: string
    personalNumber:
      name: personalNumber
      in: query
      description: Operator's number
      required: false
      schema:
        type: integer
        format: int64
    operatorId:
      name: operatorId
      in: path
      description: Operator's id
      required: true
      schema:
        type: integer
        format: int64


  schemas:
    OperatorDTO:
      title: "OperatorDTO"
      type: object
      description: Data transfer object for Operator entity
      required:
        - name
        - personalNumber
      properties:
        name:
          type: string
          example: 'Bob'
        personalNumber:
          type: integer
          example: 1234
    ExceptionModel:
      title: "OperatorDTO"
      type: object
      description: Service error
      properties:
        message:
          type: string
          example: 'Entity not found'
        timestamp:
          type: string
          example: "2023-11-01T15:06:32.976+00:00"

